version: '3'
services:
  chizutsuru:
    image: ${TAG_VERSION}
    build:
      context: .
      args:
        PORT: ${PORT}
        MYSQL_TEST_HOST: ${MYSQL_HOST}
        MYSQL_TEST_PORT: ${MYSQL_PORT}
        MYSQL_TEST_DATABASE: ${MYSQL_DATABASE}
        MYSQL_TEST_USERNAME: ${MYSQL_USERNAME}
        MYSQL_TEST_PASSWORD: ${MYSQL_PASSWORD}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
        LUCENE_FOLDER: ${LUCENE_FOLDER}