FROM maven:3.6.3-jdk-11 as builder
ARG MYSQL_HOST_ARG
ARG MYSQL_USERNAME_ARG
ARG MYSQL_PASSWORD_ARG
ARG MYSQL_PORT_ARG
ARG CHIZUTSURU_PORT
ARG MYSQL_DATABASE_ARG=JEE

ENV CHIZUTSURU_PORT $CHIZUTSURU_PORT
ENV MYSQL_PORT $MYSQL_PORT_ARG
ENV MYSQL_HOST $MYSQL_HOST_ARG
ENV MYSQL_USERNAME $MYSQL_USERNAME_ARG
ENV MYSQL_PASSWORD $MYSQL_PASSWORD_ARG
ENV MYSQL_DATABASE $MYSQL_DATABASE_ARG

WORKDIR /app

copy . .

RUN mvn clean install

FROM openjdk:11.0.6-slim

WORKDIR /app

COPY --from=builder /app/target/chizutsuru-api-0.0.1-rc0.jar /app/api.jar

EXPOSE ${CHIZUTSURU_PORT}

CMD ["java", "-jar", "api.jar"]